package edu.aku.hassannaqvi.epi_register.database

import edu.aku.hassannaqvi.epi_register.contracts.TableContracts.*
import edu.aku.hassannaqvi.epi_register.core.MainApp.PROJECT_NAME

object CreateTable {

    const val DATABASE_NAME = "$PROJECT_NAME.db"
    const val DATABASE_COPY = "${PROJECT_NAME}_copy.db"
    const val DATABASE_VERSION = 2

    const val SQL_CREATE_FORMCR = ("CREATE TABLE "
            + FormCRTable.TABLE_NAME + "("
            + FormCRTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FormCRTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FormCRTable.COLUMN_UID + " TEXT,"
            + FormCRTable.COLUMN_UUID + " TEXT,"
            + FormCRTable.COLUMN_USERNAME + " TEXT,"
            + FormCRTable.COLUMN_SYSDATE + " TEXT,"
            + FormCRTable.COLUMN_START_TIME + " TEXT,"
            + FormCRTable.COLUMN_END_TIME + " TEXT,"
            + FormCRTable.COLUMN_ISTATUS + " TEXT,"
            + FormCRTable.COLUMN_DEVICEID + " TEXT,"
            + FormCRTable.COLUMN_DEVICETAGID + " TEXT,"
            + FormCRTable.COLUMN_SYNCED + " TEXT,"
            + FormCRTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FormCRTable.COLUMN_APPVERSION + " TEXT,"
            + FormCRTable.COLUMN_CR + " TEXT"
            + " );"
            )

    const val SQL_CREATE_FORMCRFollowUP = ("CREATE TABLE "
            + FormCRFollowUPTable.TABLE_NAME + "("
            + FormCRFollowUPTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FormCRFollowUPTable.COLUMN_UID + " TEXT,"
            + FormCRFollowUPTable.COLUMN_USERNAME + " TEXT,"
            + FormCRFollowUPTable.COLUMN_SYSDATE + " TEXT,"
            + FormCRFollowUPTable.COLUMN_DEVICEID + " TEXT,"
            + FormCRFollowUPTable.COLUMN_ISTATUS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_START_TIME + " TEXT,"
            + FormCRFollowUPTable.COLUMN_END_TIME + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_DMU_REGISTER + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_REG_NUMBER + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PAGE_NUMBER + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_RSNO + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_CARD_NUMBER + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_CHILD_NAME + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_FATHER_NAME + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_AGE_MONTHS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_AGE_YEARS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_AGE_DAYS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_GENDER + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ADDRESS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PHONE + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PHONE_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_BCG + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_BCG_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_BCG_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_BCG_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_HEP_B + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_HEP_B1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_HEP_B2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_HEP_BNA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV0 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV0_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV0_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV0_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV1_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV1_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV1_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV2_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV2_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV2_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV3 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV3_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV3_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_OPV3_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA1_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA1_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA1_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA2_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA2_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_ROTA2_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_IPV + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_IPV_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_IPV_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_IPV_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV1_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV1_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV1_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV2_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV2_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV2_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV3 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV3_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV3_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PCV3_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA1_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA1_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA1_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA2_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA2_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA2_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA3 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA3_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA3_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_PENTA3_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES1_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES1_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES1_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES2_D1 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES2_D2 + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_MEASLES2_NA + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_BIRTH_STATUS + " TEXT,"
            + FormCRFollowUPTable.COLUMN_CR_COMMENTS + " TEXT"
            + " );"
            )

    const val SQL_CREATE_FORMWR = ("CREATE TABLE "
            + FormWRTable.TABLE_NAME + "("
            + FormWRTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + FormWRTable.COLUMN_PROJECT_NAME + " TEXT,"
            + FormWRTable.COLUMN_UID + " TEXT,"
            + FormWRTable.COLUMN_USERNAME + " TEXT,"
            + FormWRTable.COLUMN_SYSDATE + " TEXT,"
            + FormWRTable.COLUMN_START_TIME + " TEXT,"
            + FormWRTable.COLUMN_END_TIME + " TEXT,"
            + FormWRTable.COLUMN_ISTATUS + " TEXT,"
            + FormWRTable.COLUMN_DEVICEID + " TEXT,"
            + FormWRTable.COLUMN_DEVICETAGID + " TEXT,"
            + FormWRTable.COLUMN_SYNCED + " TEXT,"
            + FormWRTable.COLUMN_SYNCED_DATE + " TEXT,"
            + FormWRTable.COLUMN_APPVERSION + " TEXT,"
            + FormWRTable.COLUMN_WR + " TEXT"
            + " );"
            )


    const val SQL_CREATE_USERS = ("CREATE TABLE "
            + UsersTable.TABLE_NAME + "("
            + UsersTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + UsersTable.COLUMN_USERNAME + " TEXT,"
            + UsersTable.COLUMN_PASSWORD + " TEXT,"
            + UsersTable.COLUMN_ENABLED + " TEXT,"
            + UsersTable.COLUMN_ISNEW_USER + " TEXT,"
            + UsersTable.COLUMN_PWD_EXPIRY + " TEXT,"
            + UsersTable.COLUMN_FULLNAME + " TEXT"
            + " );"
            )

    const val SQL_ALTER_USERS_ENABLED = ("Alter TABLE "
            + UsersTable.TABLE_NAME + " ADD "
            + UsersTable.COLUMN_ENABLED + " TEXT"
            + " ;"
            )

    const val SQL_ALTER_USERS_ISNEW_USER = ("Alter TABLE "
            + UsersTable.TABLE_NAME + " ADD "
            + UsersTable.COLUMN_ISNEW_USER + " TEXT"
            + " ;"
            )
    const val SQL_ALTER_USERS_PWD_EXPIRY = ("Alter TABLE "
            + UsersTable.TABLE_NAME + " ADD "
            + UsersTable.COLUMN_PWD_EXPIRY + " TEXT"
            + " ;"
            )

    const val SQL_CREATE_VERSIONAPP = ("CREATE TABLE "
            + VersionTable.TABLE_NAME + " ("
            + VersionTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + VersionTable.COLUMN_VERSION_CODE + " TEXT, "
            + VersionTable.COLUMN_VERSION_NAME + " TEXT, "
            + VersionTable.COLUMN_PATH_NAME + " TEXT "
            + ");"
            )

    const val SQL_CREATE_ENTRYLOGS = ("CREATE TABLE "
            + EntryLogTable.TABLE_NAME + "("
            + EntryLogTable.COLUMN_ID + " INTEGER PRIMARY KEY AUTOINCREMENT,"
            + EntryLogTable.COLUMN_PROJECT_NAME + " TEXT,"
            + EntryLogTable.COLUMN_UID + " TEXT,"
            + EntryLogTable.COLUMN_UUID + " TEXT,"
            + EntryLogTable.COLUMN_USERNAME + " TEXT,"
            + EntryLogTable.COLUMN_SYSDATE + " TEXT,"
            + EntryLogTable.COLUMN_DEVICEID + " TEXT,"
            + EntryLogTable.COLUMN_ENTRY_DATE + " TEXT,"
            + EntryLogTable.COLUMN_ISTATUS + " TEXT,"
            + EntryLogTable.COLUMN_ISTATUS96x + " TEXT,"
            + EntryLogTable.COLUMN_SYNCED + " TEXT,"
            + EntryLogTable.COLUMN_SYNC_DATE + " TEXT,"
            + EntryLogTable.COLUMN_APPVERSION + " TEXT"
            + " );"
            )
}